/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package poly.edu.ui;

import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import poly.edu.dao.HangXeDAO;
import poly.edu.dao.LoaiXeDAO;
import poly.edu.dao.MauXeDAO;
import poly.edu.entity.LoaiXe;
import poly.edu.entity.MauXe;
import poly.edu.helper.DiaLogHelper;
import poly.edu.helper.ImageHelper;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import poly.edu.dao.SanPhamDAO;
import poly.edu.entity.HangXe;
import poly.edu.entity.SanPham;
import poly.edu.helper.ShareHelper;
import poly.edu.helper.utilityHelper;

/**
 *
 * @author pdo18
 */
public class SanPhamlFrame extends javax.swing.JInternalFrame {
    
    private DefaultTableModel model;
    SanPhamDAO dao = new SanPhamDAO();
    MauXeDAO maudao = new MauXeDAO();
    HangXeDAO hangdao = new HangXeDAO();
    LoaiXeDAO loaidao = new LoaiXeDAO();
    int index = 0;  

    /**
     * Creates new form SanPhamlFrame
     */
    public SanPhamlFrame() {
        initComponents();
        initTable();
        init();
        fillComboBoxHangXe();
    }

    private void initTable() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{" Mã Xe", "Tên", "Hãng", "Màu", "Số Máy", "Gía", " Loại Xe", "Số Khung", "Dung Tích", "Số Lượng", "Hình"});
        tblThongTinXe.setModel(model);
    }

    private void fillTable() { // đổ dữ liệu lên Table
        DefaultTableModel model = (DefaultTableModel) tblThongTinXe.getModel();  // tao nơi chưa dữ liệu hiện lên table
        model.setRowCount(0);        
        try {
            List<SanPham> list = dao.selectAll();
            for (SanPham ttx : list) {
                Object[] row = {
                    ttx.getMaXe(),
                    ttx.getTenXe(),
                    ttx.getTenHang(),
                    ttx.getTenMau(),
                    ttx.getSoMay(),
                    ttx.getGia(),
                    ttx.getLoaiXe(),
                    ttx.getSoKhung(),
                    ttx.getDungTich(),
                    ttx.getSoLuong(),
                    ttx.getHinh()};
                model.addRow(row); //bỏ vào từng hàng của bảng
            }
        } catch (Exception e) {
            DiaLogHelper.showErrorDialog(this, e.getMessage(), "Lỗi Truy Vấn Dữ Liệu !");
        }
        
    }
    public boolean checkNullHinh() {
        if (lblHinh.getToolTipText() != null) {
            return true;
        } else {
            DiaLogHelper.alert(this, "Không được để trống hình.");
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSoKhung = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnTuyChonLoai = new javax.swing.JButton();
        cboHangXe = new javax.swing.JComboBox<>();
        txtSoLuong = new javax.swing.JTextField();
        btnNhapMoi = new javax.swing.JButton();
        btnTuyChonHang = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSoMay = new javax.swing.JTextField();
        lblHinh = new javax.swing.JLabel();
        btnTuyChonMau = new javax.swing.JButton();
        cboLoaiXe = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboMauXe = new javax.swing.JComboBox<>();
        txtDungTich = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongTinXe = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1385, 718));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÍ SẢN PHẨM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"));

        jLabel8.setText("Màu xe:");

        jLabel6.setText("Giá xe:");

        jLabel12.setText("Số khung:");

        btnTuyChonLoai.setBackground(new java.awt.Color(153, 153, 153));
        btnTuyChonLoai.setText("Thêm");
        btnTuyChonLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuyChonLoaiActionPerformed(evt);
            }
        });

        cboHangXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNhapMoi.setBackground(new java.awt.Color(153, 153, 153));
        btnNhapMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/icons/Clear-icon.png"))); // NOI18N
        btnNhapMoi.setText("Mới");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        btnTuyChonHang.setBackground(new java.awt.Color(153, 153, 153));
        btnTuyChonHang.setText("Thêm");
        btnTuyChonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuyChonHangActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(153, 153, 153));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/icons/Edit.png"))); // NOI18N
        btnSua.setText("sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(153, 153, 153));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/icons/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel7.setText("Hãng xe:");

        lblHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        btnTuyChonMau.setBackground(new java.awt.Color(153, 153, 153));
        btnTuyChonMau.setText("Thêm");
        btnTuyChonMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuyChonMauActionPerformed(evt);
            }
        });

        cboLoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Dung tích:");

        cboMauXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Số máy:");

        btnThem.setBackground(new java.awt.Color(153, 153, 153));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/icons/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel5.setText("Tên xe:");

        jLabel9.setText("Loại xe:");

        jLabel13.setText("Số lượng:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cboHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTuyChonHang))
                            .addComponent(txtTenXe)
                            .addComponent(txtGia)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboLoaiXe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTuyChonMau)
                            .addComponent(btnTuyChonLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel10))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(15, 15, 15)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSoKhung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                .addComponent(txtSoMay, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDungTich, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtDungTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtSoMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cboHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTuyChonHang))
                        .addGap(30, 30, 30)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(cboLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTuyChonLoai))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cboMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTuyChonMau)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblThongTinXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblThongTinXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinXeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThongTinXe);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1373, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblThongTinXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinXeMouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 1) {
            this.index = tblThongTinXe.rowAtPoint(evt.getPoint());
            this.edit();
        }
    }//GEN-LAST:event_tblThongTinXeMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (utilityHelper.checkNullText(txtTenXe)
                && utilityHelper.checkNullText(txtGia)
                && utilityHelper.checkNullText(txtDungTich)
                && utilityHelper.checkNullText(txtSoLuong)
                && checkNullHinh()) {
            if (utilityHelper.checkNullText(txtTenXe)
                    && utilityHelper.checkNullText(txtGia)
                    && utilityHelper.checkNullText(txtDungTich)
                    && utilityHelper.checkNullText(txtSoLuong)) {
                this.insert();
            }
        }
        return;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTuyChonMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuyChonMauActionPerformed
        // TODO add your handling code here:
        new MauXeJFrame().setVisible(true);
    }//GEN-LAST:event_btnTuyChonMauActionPerformed

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.index = tblThongTinXe.getSelectedRow();
            chonAnh();
        }
    }//GEN-LAST:event_lblHinhMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (ShareHelper.USER.isChucVu() == true) {
            this.delete();
        } else {
            JOptionPane.showMessageDialog(this, "Chỉ Quản lý mới được xóa");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTuyChonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuyChonHangActionPerformed
        // TODO add your handling code here:
        new HangXeJFrame().setVisible(true);
    }//GEN-LAST:event_btnTuyChonHangActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        // TODO add your handling code here:
        this.clearFrom();
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnTuyChonLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuyChonLoaiActionPerformed
        // TODO add your handling code here:
        new LoaiXeFrame().setVisible(true);
    }//GEN-LAST:event_btnTuyChonLoaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTuyChonHang;
    private javax.swing.JButton btnTuyChonLoai;
    private javax.swing.JButton btnTuyChonMau;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboHangXe;
    private javax.swing.JComboBox<String> cboLoaiXe;
    private javax.swing.JComboBox<String> cboMauXe;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JTable tblThongTinXe;
    private javax.swing.JTextField txtDungTich;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtSoKhung;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoMay;
    private javax.swing.JTextField txtTenXe;
    // End of variables declaration//GEN-END:variables

    void init() {
        fillComboBoxLoaiXe();
        fillComboBoxMauXe();
        fillTable();
    }

    private void setForm(SanPham ttx) {
        txtTenXe.setText(ttx.getTenXe());
        String mahang = (String) tblThongTinXe.getValueAt(this.index, 2);
        HangXe hx = hangdao.selectById(mahang);
        cboHangXe.setSelectedItem(hx);
        String mamau = (String) tblThongTinXe.getValueAt(this.index, 3);
        MauXe mx = maudao.selectById(mamau);
        cboMauXe.setSelectedItem(mx);
        txtSoMay.setText(ttx.getSoMay());
        txtGia.setText(ttx.getGia() + "");
        String maloai = (String) tblThongTinXe.getValueAt(this.index, 6);
        LoaiXe lx = loaidao.selectById(maloai);
        cboLoaiXe.setSelectedItem(lx);
        txtSoKhung.setText(ttx.getSoKhung());
        txtDungTich.setText(ttx.getDungTich());
        txtSoLuong.setText(ttx.getSoLuong() + "");
        if (ttx.getHinh() != null) {
            lblHinh.setToolTipText(ttx.getHinh());
            lblHinh.setIcon(ImageHelper.read(ttx.getHinh()));
        }

    }

    private SanPham getForm() { // tạo 1 nhanvien từ form
        SanPham ttx = new SanPham();

        ttx.setTenXe(txtTenXe.getText());
        HangXe hx = (HangXe) cboHangXe.getSelectedItem();
        ttx.setTenHang(hx.getMaHang());
        MauXe mx = (MauXe) cboMauXe.getSelectedItem();
        ttx.setTenMau(mx.getMaMau());
        ttx.setSoMay(txtSoMay.getText());
        ttx.setGia(Float.valueOf(txtGia.getText()));
        LoaiXe lx = (LoaiXe) cboLoaiXe.getSelectedItem();
        ttx.setLoaiXe(lx.getMaLoai());
        ttx.setSoKhung(txtSoKhung.getText());
        ttx.setDungTich(txtDungTich.getText());
        ttx.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
        ttx.setHinh(lblHinh.getToolTipText());
        return ttx;
    }

    private SanPham getUpdate() { // tạo 1 nhanvien từ form

        SanPham ttx = new SanPham();
        Integer MaSp = (int) tblThongTinXe.getValueAt(this.index, 0);
        ttx.setMaXe(MaSp);
        ttx.setTenXe(txtTenXe.getText());
        HangXe hx = (HangXe) cboHangXe.getSelectedItem();
        ttx.setTenHang(hx.getMaHang());
        MauXe mx = (MauXe) cboMauXe.getSelectedItem();
        ttx.setTenMau(mx.getMaMau());
        ttx.setSoMay(txtSoMay.getText());
        ttx.setGia(Float.valueOf(txtGia.getText()));
        LoaiXe lx = (LoaiXe) cboLoaiXe.getSelectedItem();
        ttx.setLoaiXe(lx.getMaLoai());
        ttx.setSoKhung(txtSoKhung.getText());
        ttx.setDungTich(txtDungTich.getText());
        ttx.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
        ttx.setHinh(lblHinh.getToolTipText());
        return ttx;
    }

    public void fillComboBoxHangXe() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboHangXe.getModel();
        cboHangXe.removeAllItems();
        List<HangXe> list = hangdao.selectAll();
        for (HangXe h : list) {
            model.addElement(h);
        }
    }

    void fillComboBoxMauXe() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMauXe.getModel();
        cboMauXe.removeAllItems();
        List<MauXe> list = maudao.selectAll();
        for (MauXe m : list) {
            model.addElement(m);
        }
    }

    void fillComboBoxLoaiXe() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiXe.getModel();
        cboLoaiXe.removeAllItems();
        List<LoaiXe> list = loaidao.selectAll();
        for (LoaiXe v : list) {
            model.addElement(v);
        }
    }

    private void insert() {
        SanPham ttx = getForm();
        try {
            dao.insert(ttx);
            this.fillTable();
            this.clearFrom();
            DiaLogHelper.alert(this, "Thêm Mới Thành Công");
        } catch (Exception e) {
            DiaLogHelper.showErrorDialog(this, e.getMessage(), "Thêm Mới Thất Bại!");
        }
    }

    private void update() {
        SanPham ttx = getUpdate();
        try {
            dao.update(ttx);
            this.fillTable();
            this.clearFrom();
            DiaLogHelper.alert(this, "Cập Nhật Thành Công");
        } catch (Exception e) {
            DiaLogHelper.showErrorDialog(this, e.getMessage(), "Cập nhật Thất Bại!");
        }
    }

    public void delete() {
        if (DiaLogHelper.confirm(this, "Bạn có muốn xóa hoa don này ?")) {
            Integer makh = (Integer) tblThongTinXe.getValueAt(this.index, 0);
            try {
                dao.delete(makh);
                this.fillTable();
                this.clearFrom();
                DiaLogHelper.alert(this, "Xóa Thành Công");
            } catch (Exception e) {
                DiaLogHelper.showErrorDialog(this, e.getMessage(), "Xóa Thật Thất Bại!");
            }
        }
    }

    private void clearFrom() {
        SanPham ttx = new SanPham();
        this.setForm(ttx);

    }

    private void edit() {
        Integer manv = (Integer) tblThongTinXe.getValueAt(this.index, 0);
        SanPham ttx = dao.selectById(manv);
        this.setForm(ttx);
    }

    private void chonAnh() {
        if (FileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = FileChooser.getSelectedFile();
            ImageHelper.save(file);
            ImageIcon icon = ImageHelper.read(file.getName());
            lblHinh.setIcon(icon);
            lblHinh.setToolTipText(file.getName());
        }
    }
}
